### ISSUE TITLE
time

### ISSUE THREAD

**Issue by ronaldhacker** [robjohnc/nightscout_wemos_epaper#2]
Not really an issue per say...

I can't figure out how to get the code to output the correct time for my timezone. US/Eastern 

I have tried everything!

**Comment by robjohnc** [comment]
You could use something like [JChristensen's Timezone](https://github.com/JChristensen/Timezone) library, get rid of the "isBST" function and it's calls from our code, and then use something like this in setup:
```
time_t eastern, utc;
TimeChangeRule usEDT = {"EDT", Second, Sun, Mar, 2, -240};  //UTC - 4 hours
TimeChangeRule usEST = {"EST", First, Sun, Nov, 2, -300};   //UTC - 5 hours
Timezone usEastern(usEDT, usEST);
```
and when you call the showdata function use:
```
//call the "showdata" function to show the data on the LCD screen
showdata(usEastern.toLocal(timeNow),bgs0_sgv,dataAge,getVcc);
```
