### ISSUE TITLE
OLED Display

### ISSUE THREAD

**Issue by LosBagros** [robjohnc/nightscout_wemos_epaper#3]
Hello,
Can someone please help me with using something similar like this on 0.96 inch OLED I2C Display connected with wemos d1 mini.
Thank you.

**Comment by robjohnc** [comment]
It depends on the actual display you are using - I would find a library for that display and then do a few test sketches to position the information on there as you need.

**Comment by LosBagros** [comment]
If you can help i am using this [display](https://www.aliexpress.com/item/32643950109.html) and wemos d1 mini.
Thank you
